CREATE TABLE queue_monster (
    monster_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt VARCHAR(1000) NOT NULL,
    image CLOB
);

CREATE TABLE image_generation_job (
    job_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    monster_id BIGINT NOT NULL REFERENCES queue_monster(monster_id),
    prompt VARCHAR(1000) NOT NULL,
    status VARCHAR(16) NOT NULL CHECK (CASE status
        WHEN 'PENDING' THEN TRUE WHEN 'RUNNING' THEN TRUE
        WHEN 'SUCCEEDED' THEN TRUE WHEN 'FAILED' THEN TRUE ELSE FALSE END),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    deadline_at TIMESTAMP(9) WITH TIME ZONE,
    claim_token UUID,
    created_at TIMESTAMP(9) WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP(9) WITH TIME ZONE,
    finished_at TIMESTAMP(9) WITH TIME ZONE,
    last_error VARCHAR(2000),
    CHECK (CASE status WHEN 'RUNNING'
        THEN claim_token IS NOT NULL AND deadline_at IS NOT NULL AND started_at IS NOT NULL
        ELSE claim_token IS NULL AND deadline_at IS NULL END),
    CHECK (CASE status WHEN 'SUCCEEDED' THEN finished_at IS NOT NULL
        WHEN 'FAILED' THEN finished_at IS NOT NULL ELSE finished_at IS NULL END)
);

CREATE INDEX job_ready_idx ON image_generation_job(status, next_attempt_at, job_id);
CREATE INDEX job_deadline_idx ON image_generation_job(status, deadline_at, job_id);
